apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ${K8S_STORAGES}
  name: ${K8S_STORAGES}
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
